/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function ClassroomModel(props) {
  const { nodes, materials } = useGLTF('/sceneTest2.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane.geometry}
        material={nodes.Plane.material}
        scale={[13, 1, 20]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={materials['Material.002']}
        position={[-5.763, 0.971, -4.076]}
        scale={[0.494, 0.056, 0.479]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002.geometry}
        material={materials['Material.002']}
        position={[-3.272, 0.964, -4.078]}
        scale={[0.494, 0.056, 0.479]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube003.geometry}
        material={materials['Material.002']}
        position={[-5.775, 0.971, 1.151]}
        scale={[0.494, 0.056, 0.479]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube004.geometry}
        material={materials['Material.002']}
        position={[-3.284, 0.964, 1.148]}
        scale={[0.494, 0.056, 0.479]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube006.geometry}
        material={materials['Material.002']}
        position={[3.014, 0.971, 1.151]}
        scale={[0.494, 0.056, 0.479]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube007.geometry}
        material={materials['Material.002']}
        position={[5.505, 0.964, 1.148]}
        scale={[0.494, 0.056, 0.479]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube008.geometry}
        material={materials['Material.002']}
        position={[3.014, 0.971, -4.659]}
        scale={[0.494, 0.056, 0.479]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube009.geometry}
        material={materials['Material.002']}
        position={[5.505, 0.964, -4.661]}
        scale={[0.494, 0.056, 0.479]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube010.geometry}
        material={materials['Material.002']}
        position={[10.587, 0.964, -15.414]}
        rotation={[-Math.PI, 0.824, -Math.PI]}
        scale={[0.494, 0.056, 0.479]}
      />
      <group
        position={[-9.912, 0, -18.718]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[1.566, 1.2, 1.865]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube033.geometry}
          material={materials['BrownDark.049']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube033_1.geometry}
          material={materials['PurpleDark.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube033_2.geometry}
          material={materials['White.034']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube033_3.geometry}
          material={materials['Metal.080']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube033_4.geometry}
          material={materials['BlueDark.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube033_5.geometry}
          material={materials['GreenDark.007']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube033_6.geometry}
          material={materials['WoodDark.005']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube033_7.geometry}
          material={materials['StoneDark.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube033_8.geometry}
          material={materials['Black.030']}
        />
      </group>
      <group
        position={[-11.603, 0.006, -16.724]}
        rotation={[Math.PI / 2, 0, -1.549]}
        scale={[1.566, 1.223, 1.865]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube008_1.geometry}
          material={materials['BrownDark.049']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube008_2.geometry}
          material={materials['PurpleDark.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube008_3.geometry}
          material={materials['White.034']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube008_4.geometry}
          material={materials['Metal.080']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube008_5.geometry}
          material={materials['BlueDark.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube008_6.geometry}
          material={materials['GreenDark.007']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube008_7.geometry}
          material={materials['WoodDark.005']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube008_8.geometry}
          material={materials['StoneDark.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube008_9.geometry}
          material={materials['Black.030']}
        />
      </group>
      <group
        position={[0.156, 1.509, -11.546]}
        rotation={[Math.PI / 6, 0, 0]}
        scale={[0.733, 0.695, 0.463]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_1.geometry}
          material={materials.SolarCell}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_2.geometry}
          material={materials['Material.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_3.geometry}
          material={materials.Aluminium}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube005.geometry}
        material={materials.Aluminium}
        position={[0.024, 1.367, -11.545]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.251, 0.598, 0.733]}
      />
      <group
        position={[8.622, 1.465, -14.119]}
        rotation={[0, 0.702, 0]}
        scale={[2.796, 2.712, 3.147]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube007_1.geometry}
          material={materials.MetalBlack}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube007_2.geometry}
          material={materials.DeskWood}
        />
      </group>
      <group
        position={[-4.332, 1.187, -5.989]}
        rotation={[0, -1.568, 0]}
        scale={[2.796, 2.712, 3.147]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube002_1.geometry}
          material={materials.MetalBlack}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube002_2.geometry}
          material={materials.DeskWood}
        />
      </group>
      <group
        position={[4.232, 1.187, -5.989]}
        rotation={[0, -1.568, 0]}
        scale={[2.796, 2.712, 3.147]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube003_1.geometry}
          material={materials.MetalBlack}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube003_2.geometry}
          material={materials.DeskWood}
        />
      </group>
      <group
        position={[-4.332, 1.187, -0.289]}
        rotation={[0, -1.568, 0]}
        scale={[2.796, 2.712, 3.147]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004_1.geometry}
          material={materials.MetalBlack}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004_2.geometry}
          material={materials.DeskWood}
        />
      </group>
      <group
        position={[4.232, 1.187, -0.289]}
        rotation={[0, -1.568, 0]}
        scale={[2.796, 2.712, 3.147]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube006_1.geometry}
          material={materials.MetalBlack}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube006_2.geometry}
          material={materials.DeskWood}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/sceneTest2.glb')
